
version: '3'

name: clean-architecture-rust

services:
  application:
    build: 
      context: ../
      dockerfile: .docker/rust/Dockerfile
    # container_name: rust_api
    ports:
      - 8180:8000
    depends_on:
      - database
      - phpmyadmin
    volumes:
      - ../app:/clean-architecture-rust
    networks:
      - clean-architecture-rust-network
# http://localhost/api/xxxxx -> アクセス確認

  database:
    build:
      context: ../
      dockerfile: .docker/mysql/Dockerfile
    container_name: database
    ports:
      - 3306:3306
    expose:
      - 3306
    # platform: linux/x86_64
    # 仔細は省略しますが、alwaysを選択すると
    # dockerデーモンとOSホストの再起動時にコンテナも再起動してくれるらしい
    restart: always
    env_file:
      - ../mysql/config/.env
    # コンテナ外からの接続権限を与える
    environment:
      - MYSQL_ROOT_HOST=%
    volumes:
      - ../mysql/data:/var/lib/mysql
      - ../mysql/sql:/sql
    networks:
        - clean-architecture-rust-network
  
  phpmyadmin:
    image: phpmyadmin:5
    restart: always
    container_name: clean-architecture-rust_phpmyadmin
    ports:
        - 8181:8000
    environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - PMA_USER=root
        - PMA_PASSWORD=password
        # - VIRTUAL_HOST=
    networks:
        - clean-architecture-rust-network

networks:
  clean-architecture-rust-network:
    name: clean_architecture_rust_network
