
version: '3'

name: clean-archtecture-rust

services:
  application:
    build: 
      context: ../
      dockerfile: .docker/rust/Dockerfile
    # container_name: rust_api
    ports:
      - 8000:8000
    volumes:
      - ../app:/clean-archtecture-rust
